# Oh yeah!
language: node_js

# Add additional versions here as appropriate.
node_js:
  - "stable"

# Lint errors should trigger a failure.
before_script: npm run lint

# Runs the coverage script (which runs the tests)
script: npm run cover

# Code coverage
after_success: npm run coveralls
